apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts.sockshop-staging.23.251.142.10.xip.io
  - carts
  http:
  - route:
    - destination:
        host: carts-canary.sockshop-staging.svc.cluster.local
      weight: 100
    - destination:
        host: carts-primary.sockshop-staging.svc.cluster.local
