apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-12T14:02:32Z"
  name: carts-primary
  resourceVersion: "957798"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 1e6cffc4-646a-11ea-b24f-42010a84013c
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts-primary
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
